import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./navigation/header";
import { use, useState } from 'react';
import { UserIcon } from "../../public/icons/icons";


import { SIDENAV_ITEMS } from "./data/sidebar";
import DropdownLink from "./components/dropdown-link";
import Navigation from "./components/navigation";


const inter = Inter({ subsets: ["latin"] });

const monstserrat = Montserrat({
    subsets: ["latin"],
    weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
    title: "Codero - Page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={monstserrat.className}>
                <Navigation>
                    {children}
                </Navigation>
            </body>
        </html>
    );
}
