import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "./navigation/sidebar";
import Header from "./navigation/header";
import { useState } from 'react';

const inter = Inter({ subsets: ["latin"] });

const monstserrat = Montserrat({
    subsets: ["latin"],
    weight: ['400', '500', '600', '700']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    // help me code my <Header/> 

    return (
        <html lang="en">
            <body className={monstserrat.className}>
                {/* <main className="flex">
                    <Sidebar />

                    <div id="page_right" className="w-right">
                        <Header />
                        {children}
                    </div>
                </main> */}


                {children}
            </body>
        </html>
    );
}
