import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

import Navigation from "../components/sidebar/navigation"

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
    title: "Codero - Page",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <Navigation>
                    {children}
                </Navigation>
            </body>
        </html>
    );
}
